Capitalization_Dict = {
'dmg': 'DMG',
'delay': 'Delay',
'def': 'DEF',
'hp': 'HP',
'mp': 'MP',
'str': 'STR',
'dex': 'DEX',
'vit': 'VIT',
'agi': 'AGI',
'int': 'INT',
'mnd': 'MND',
'chr': 'CHR',
'fire': 'Fire',
'ice': 'Ice',
'wind': 'Wind',
'earth': 'Earth',
'thunder': 'Thunder',
'water': 'Water',
'light': 'Light',
'dark': 'Dark',
'attack': 'Attack',
'rangedattack': 'Ranged Attack',
'accuracy': 'Accuracy',
'rangedaccuracy': 'Ranged Accuracy',
'magicattackbonus': 'Magic Atk. Bonus',
'magicatkbonus': 'Magic Atk. Bonus',
'magicdamage': 'Magic damage',
'magicaccuracy': 'Magic Accuracy',
'evasion': 'Evasion',
'magicevasion': 'Magic Evasion',
'magicdefbonus': 'Magic Def. Bonus',
'magicdefensebonus': 'Magic Def. Bonus',
'regen': 'Regen',
'refresh': 'Refresh',
'damagetaken': 'Damage taken',
'haste': 'Haste',
'rangeddelay': 'Ranged Delay',
'snapshot': 'Snapshot',
'rapidshot': 'Rapid Shot',
'recycle': 'Recycle',
'zanshin': 'Zanshin',
'storetp': 'Store TP',
'weaponskillaccuracy': 'Weaponskill Accuracy',
'weaponskilldamage': 'Weaponskill damage',
'doubleattack': 'Double Attack',
'doubleattackdamage': 'Double Attack damage',
'tripleattack': 'Triple Attack',
'tripleattackdamage': 'Triple Attack damage',
'quadattack': 'Quad Attack',
'berserkduration': 'Berserk Duration',
'augmentssa': 'Augments SA',
'augmentsta': 'Augments TA',
'criticalhitrate': 'Critical hit rate',
'criticalhitdamage': 'Critical hit damage',
'enmity': 'Enmity',
'counter': 'Counter',
'counterstance': 'Counterstance',
'chakra': 'Chakra',
'curepotency': 'Cure potency',
'curespellcastingtime': 'Cure spellcasting time',
'curecastingtime': 'Cure spellcasting time',
'elementalresistancespells': 'Elemental resistance spells',
'spellinteruptionrate': 'Spell interruption rate down',
'conservemp': 'Conserve MP',
'elementalcelerity': 'Elemental Celerity',
'enspelldamagebonus': 'Enspell damage bonus',
'steal': 'Steal',
'shieldbash': 'Shield Bash',
'weaponbash': 'Weapon Bash',
'kickattacksdamage': 'Kick Attacks damage',
'fastcast': 'Fast Cast',
'quickmagic': 'Quick Magic',
'subtleblow': 'Subtle Blow',
'absorbduration': 'Absorb Duration',
'charm': 'Charm',
'tamesuccessrate': 'Tame Success Rate',
'reward': 'Reward',
'enfeeblingpotency': 'Enfeebling Potency',
'allsongs': 'All Songs',
'maximumsongs': 'Maximum Songs',
'songduration': 'Song Duration',
'songspellcastingtime': 'Song spellcasting time',
'songcastingtime': 'Song spellcasting time',
'ninjatoolexpertise': 'Ninja tool expertise',
'songrecastdelay': 'Song Recast Delay',
'avatarlevel': 'Avatar level',
'avatarperpetuationcost': 'Avatar Perpetuation Cost',
'bloodpactdamage': 'Blood Pact damage',
'bloodpactabilitydelay': 'Blood Pact ability delay',
'dualwield': 'Dual Wield',
'jumptpbonus': 'Jump TP Bonus',
'movementspeed': 'Movement speed',
'hand-to-handskill': 'Hand-to-Hand skill',
'daggerskill': 'Dagger skill',
'swordskill': 'Sword skill',
'greatswordskill': 'Great Sword skill',
'axeskill': 'Axe skill',
'greataxeskill': 'Great Axe skill',
'scytheskill': 'Scythe skill',
'polearmskill': 'Polearm skill',
'katanaskill': 'Katana skill',
'greatkatanaskill': 'Great Katana skill',
'clubskill': 'Club skill',
'staffskill': 'Staff skill',
'archeryskill': 'Archery skill',
'marksmanshipskill': 'Marksmanship skill',
'throwskill': 'Throw skill',
'guardingskill': 'Guarding skill',
'evasionskill': 'Evasion skill',
'shieldskill': 'Shield skill',
'parryingskill': 'Parrying skill',
'divinemagicskill': 'Divine magic skill',
'healingmagicskill': 'Healing magic skill',
'enhancingmagicskill': 'Enhancing magic skill',
'enfeeblingmagicskill': 'Enfeebling magic skill',
'elementalmagicskill': 'Elemental magic skill',
'darkmagicskill': 'Dark magic skill',
'summoningmagicskill': 'Summoning magic skill',
'ninjutsuskill': 'Ninjutsu skill',
'singingskill': 'Singing skill',
'stringinstrumentskill': 'String instrument skill',
'windinstrumentskill': 'Wind instrument skill',
'fireaffinity': 'Fire Affinity',
'iceaffinity': 'Ice Affinity',
'windaffinity': 'Wind Affinity',
'earthaffinity': 'Earth Affinity',
'thunderaffinity': 'Thunder Affinity',
'wateraffinity': 'Water Affinity',
'lightaffinity': 'Light Affinity',
'darkaffinity': 'Dark Affinity',
'slashingdamagetaken': 'Slashing damage taken',
'piercingdamagetaken': 'Piercing damage taken',
'impactdamagetaken': 'Impact damage taken',
'hand-to-handdamagetaken': 'Hand-to-Hand damage taken',
'handtohanddamagetaken': 'Hand-to-Hand damage taken',
'physicaldamagetaken': 'Physical damage taken',
'magicdamagetaken': 'Magic damage taken',
'breathdamage taken': 'Breath damage taken',
'resistamnesia': 'Resist Amnesia',
'resistbind': 'Resist Bind',
'resistblind': 'Resist Blind',
'resistgravity': 'Resist Gravity',
'resistparalyze': 'Resist Paralyze',
'resistpetrify': 'Resist Petrify',
'resistpoison': 'Resist Poison',
'resistsilence': 'Resist Silence',
'resistsleep': 'Resist Sleep',
'resistslow': 'Resist Slow',
'resistvirus': 'Resist Virus',
'aquankiller': 'Aquan Killer',
'arcanakiller': 'Arcana Killer',
'amorphkiller': 'Amorph Killer',
'beastkiller': 'Beast Killer',
'birdkiller': 'Bird Killer',
'demonkiller': 'Demon Killer',
'dragonkiller': 'Dragon Killer',
'emptykiller': 'Empty Killer',
'humanoidkiller': 'Humanoid Killer',
'lizardkiller': 'Lizard Killer',
'lumoriankiller': 'Lumorian KIller',
'luminionkiller': 'Luminion Killer',
'plantoidkiller': 'Plantoid Killer',
'undeadkiller': 'Undead Killer',
'verminkiller': 'Vermin Killer',
'superiorlv': 'Superior Lv',
'mprecoveredwhilehealing': 'MP Recovered while healing',
'hprecoveredwhilehealing': 'HP Recovered while healing',
'fishingskill': 'Fishing skill',
'woodworkingskill': 'Woodworking skill',
'smithingskill': 'Smithing skill',
'goldsmithingskill': 'Goldsmithing skill',
'clothcraftskill': 'Clothcraft skill',
'leathercraftskill': 'Leathercraft skill',
'bonecraftskill': 'Bonecraft skill',
'alchemyskill': 'Alchemy skill',
'cookingskill': 'Cooking skill',
'synergyskill': 'Synergy skill',
'ridingskill': 'Riding skill',
'convertshptomp': 'Converts HP to MP',
'convertsmptohp': 'Converts MP to HP',
'divinecaress': 'Divine Caress',
'regeneffect duration': 'Regen effect duration',
'phalanx': 'Phalanx',
'drainandaspirpotency': 'Drain and Aspir potency',
'meditateduration': 'Meditate duration',
'warcryduration': 'Warcry duration',
'aggressor': 'Aggressor',
'bloodpactrecasttimeii': 'Blood Pact recast time II',
'elementalsiphon': 'Elemental Siphon',
'slow': 'Slow',
'occasionallyattackstwice': 'Occasionally attacks twice',
'occasionallyattacksthrice': 'Occasionally attacks thrice',
'occasionallyattacksmax': 'Occasionally attacks 2 to ',
'testtestdt': 'Test Test DT',
'cursna': 'Cursna',
'skillchaindamage': 'Skillchain damage',
'retaliationdamage': 'Retaliation damage',
'focus': 'Focus',
'hhdmg': 'HHDMG',
'hhdelay': 'HHDelay',
'weaponskilldex': 'Weapon skill DEX',
'weaponskillstr': 'Weapon skill STR',
'weaponskillvit': 'Weapon skill VIT',
'weaponskillagi': 'Weapon skill AGI',
'weaponskillint': 'Weapon skill INT',
'weaponskillmnd': 'Weapon skill MND',
'weaponskillchr': 'Weapon skill CHR',
'resistancetoallstatusailments': 'Resistance to all status ailments',
'tpbonus': 'TP Bonus',
'breathdamagetaken': 'Breath damage taken',
'magiccriticalhitrate': 'Magic critical hit rate',
}

Partial_Correction = {
'Cure potency': '"Cure" potency',
'Cure spellcasting time': '"Cure" spellcasting time',
'Kick Attacks damage': '"Kick Attacks" damage',
'Blood Pact damage': '"Blood Pact" damage',
'Blood Pact ability delay': '\Blood Pact" ability delay',
'Regen effect duration': '"Regen" effect duration',
'Drain and Aspir potency': '"Drain" and "Aspir" potency',
'Meditate duration': '"Meditate" duration',
'Warcry duration': '"Warcry" duration',
'Blood Pact recast time II': '"Blood Pact" recast time II',
'Retaliation damage': '"Retaliation" damage',
}

quoted_stat = [
'Magic Def. Bonus',
'Magic Atk. Bonus',
'Store TP',
'Snapshot',
'Recycle',
'Rapid Shot',
'Double Attack',
'Triple Attack',
'Quad Attack',
'Charm',
'Refresh',
'Regen',
'Regain',
'Resist Amnesia',
'Resist Bind',
'Resist Blind',
'Resist Gravity',
'Resist Paralyze',
'Resist Petrify',
'Resist Poison',
'Resist Silence',
'Resist Sleep',
'Resist Slow',
'Resist Virus',
'Aquan Killer',
'Arcana Killer',
'Amorph Killer',
'Beast Killer',
'Bird Killer',
'Demon Killer',
'Dragon Killer',
'Empty Killer',
'Humanoid Killer',
'Lizard Killer',
'Lumorian KIller',
'Luminion Killer',
'Plantoid Killer',
'Undead Killer',
'Vermin Killer',
'Chakra',
'Ninja tool expertise',
'Magic Def. Bonus',
'Phalanx',
'Aggressor',
'Elemental Siphon',
'Cursna',
'Focus',
'TP Bonus',
]

Partial_Quotation = [
'Cure potency',
'Cure spellcasting time',
'Kick Attacks damage',
'Blood Pact damage',
'Blood Pact ability delay',
'Regen effect duration',
'Drain and Aspir potency',
'Meditate duration',
'Warcry duration',
'Blood Pact recast time II',
'Retaliation damage',
]

ModID_Dict = {
'def': '1',
'def%': '63',
'hp': '2',
'hp%': '3',
'mp': '5',
'mp%': '6',
'str': '8',
'dex': '9',
'vit': '10',
'agi': '11',
'int': '12',
'mnd': '13',
'chr': '14',
'attack': '23',
'attack%': '62',
'rangedattack': '24',
'randgedattack%': '66',
'accuracy': '25',
'rangedaccuracy': '26',
'magicatkbonus': '28',
'magicdamage': '311',
'magicaccuracy': '30',
'evasion': '68',
'magicevasion': '31',
'magicdefbonus': '29',
'regen': '370',
'refresh': '369',
'damagetaken': '160',
'haste': '384',
'delay': '171',
'rangeddelay': '172',
'snapshot': '365',
'rapidshot': '359',
'recycle': '305',
'zanshin': '306',
'storetp': '73',
'weaponskillaccuracy': '48',
'weaponskilldamage': '840',
'doubleattack': '288',
'doubleattackdamage': '408',
'tripleattack': '302',
'tripleattackdamage': '409',
'quadattack': '430',
'berserkduration': '954',
'augmentssa': '526',
'augmentsta': '527',
'criticalhitrate': '165',
'criticalhitdamage': '421',
'enmity': '27',
'counter': '291',
'counterstance': '543',
'chakra': '123',
'curepotency': '374',
'curespellcastingtime': '519',
'elementalresistancespells': '567',
'spellinteruptionrate': '168',
'conservemp': '296',
'elementalcelerity': '901',
'enspelldamagebonus': '432',
'steal': '298',
'shieldbash': '385',
'weaponbash': '392',
'kickattacksdamage': '386',
'kickattacks': '289',
'fastcast': '170',
'quickmagic': '909',
'subtleblow': '289',
'absorbduration': '521',
'charm': '360',
'tamesuccessrate': '1166',
'reward': '364',
'enfeeblingpotency': '290',
'allsongs': '452',
'maximumsongs': '453',
'songduration': '454',
'songspellcastingtime': '455',
'songrecastdelay': '833',
'avatarlevel': '1040',
'avatarperpetuationcost': '371',
'bloodpactdamage': '126',
'dualwield': '259',
'jumptpbonus': '361',
'movementspeed': '169',
'hand-to-handskill': '80',
'daggerskill': '81',
'swordskill': '82',
'greatswordskill': '83',
'axeskill': '84',
'greataxeskill': '85',
'scytheskill': '86',
'polearmskill': '87',
'katanaskill': '88',
'greatkatanaskill': '89',
'clubskill': '90',
'staffskill': '91',
'archeryskill': '104',
'marksmanshipskill': '105',
'throwskill': '106',
'guardingskill': '107',
'evasionskill': '108',
'shieldskill': '109',
'parryingskill': '110',
'divinemagicskill': '111',
'healingmagicskill': '112',
'enhancingmagicskill': '113',
'enfeeblingmagicskill': '114',
'elementalmagicskill': '115',
'darkmagicskill': '116',
'summoningmagicskill': '117',
'ninjutsuskill': '118',
'singingskill': '119',
'stringinstrumentskill': '120',
'windinstrumentskill': '121',
'fireaffinity': '347',
'iceaffinity': '348',
'windaffinity': '349',
'earthaffinity': '350',
'thunderaffinity': '351',
'wateraffinity': '352',
'lightaffinity': '353',
'darkaffinity': '354',
'fire': '15',
'ice': '16',
'wind': '17',
'earth': '18',
'thunder': '19',
'water': '20',
'light': '21',
'dark': '22',
'slashingdamagetaken': '49',
'piercingdamagetaken': '50',
'impactdamagetaken': '51',
'hand-to-handdamagetaken': '52',
'physicaldamagetaken': '161',
'magicdamagetaken': '163',
'breathdamagetaken': '162',
'resistamnesia': '253',
'resistbind': '247',
'resistblind': '243',
'resistgravity': '249',
'resistparalyze': '242',
'resistpetrify': '246',
'resistpoison': '241',
'resistsilence': '244',
'resistsleep': '240',
'resistslow': '250',
'resistvirus': '245',
'aquankiller': '228',
'arcanakiller': '232',
'amorphkiller': '226',
'beastkiller': '230',
'birdkiller': '225',
'demonkiller': '234',
'dragonkiller': '233',
'emptykiller': '235',
'humanoidkiller': '236',
'lizardkiller': '227',
'lumoriankiller': '237',
'luminionkiller': '238',
'plantoidkiller': '229',
'undeadkiller': '231',
'verminkiller': '224',
'ninjatoolexpertise': '308',
'mprecoveredwhilehealing': '71',
'hprecoveredwhilehealing': '72',
'fishingskill': '127',
'woodworkingskill': '128',
'smithingskill': '129',
'goldsmithingskill': '130',
'clothcraftskill': '131',
'leathercraftskill': '132',
'bonecraftskill': '133',
'alchemyskill': '134',
'cookingskill': '135',
'synergyskill': '136',
'ridingskill': '137',
'convertshptomp': '7',
'convertsmptohp': '4',
'regeneffectduration': '339',
'phalanx': '301',
'drainandaspirpotency': '315',
'meditateduration': '94',
'breathpotency': '402',
'warcryduration': '483',
'aggressor': '955',
'bloodpactrecasttimeii': '541',
'elementalsiphon': '540',
'cursna': '310',
'skillchaindamage': '175',
'retaliationdamage': '414',
'focus': '561',
'weaponskilldex': '957',
'weaponskillstr': '980',
'weaponskillvit': '981',
'weaponskillagi': '982',
'weaponskillint': '983',
'weaponskillmnd': '984',
'weaponskillchr': '985',
'resistancetoallstatusailments': '958',
'tpbonus': '345',
'magiccriticalhitrate': '562',
}

PercentageList = [
'damagetaken',
'haste',
'slashingdamagetaken',
'piercingdamagetaken',
'impactdamagetaken',
'hand-to-handdamagetaken',
'physicaldamagetaken',
'magicdamagetaken',
'breathdamagetaken',
'breathdamagetaken',
]

lessismore = [
'damagetaken',
'slashingdamagetaken',
'piercingdamagetaken',
'impactdamagetaken',
'hand-to-handdamagetaken',
'physicaldamagetaken',
'magicdamagetaken',
'breathdamagetaken',
'songspellcastingtime',
'curespellcastingtime',
'avatarperpetuationcost',
]

PercentageinStats = [
'def%',
'hp%',
'mp%',
'attack%',
'rangedattack%',
]

ignore_list = [
'superiorlv',
'dmg',
'delay',
'occasionallyattackstwice',
'occasionallyattacksthrice',
'occasionallyattacksmax',
'hhdmg',
'hhdelay',
]

Base256 = [
'breathpotency',
]

